// vcb_resolver.c  -- see header + docs/color_handling_and_mod.md.
// Generated by scripts/extract_color_resolver.py and verified against the binary.

#include "vcb_resolver.h"

const TCColorEntry TC_COLOR_TABLE[] = {
    { 0x92ff63, 0x92ff63, 0x3e4d3e, "BUFFER" },
    { 0xffc663, 0xffc663, 0x4d453e, "AND" },
    { 0x63f2ff, 0x63f2ff, 0x384b56, "OR" },
    { 0xae74ff, 0xae74ff, 0x433d56, "XOR" },
    { 0xff628a, 0xff628a, 0x4d3744, "NOT" },
    { 0xffa200, 0xffa200, 0x4d392f, "NAND" },
    { 0x30d9ff, 0x30d9ff, 0x1a3c56, "NOR" },
    { 0xa600ff, 0xa600ff, 0x3b2854, "XNOR" },
    { 0x63ff9f, 0x63ff9f, 0x384d47, "LATCH_ON" },
    { 0x384d47, 0x63ff9f, 0x384d47, "LATCH_OFF" },
    { 0xff0041, 0xff0041, 0x4d243c, "CLOCK" },
    { 0xffffff, 0xffffff, 0x323841, "LED" },
    { 0xa3ff61, 0xa3ff61, 0x384d38, "VMEM_LATCH_ADDRESS" },
    { 0x61ff61, 0x61ff61, 0x384d3f, "VMEM_LATCH_CONTENT" },
    { 0xc0ff61, 0xc0ff61, 0x3d4d38, "VINPUT_COMPONENT" },
    { 0xff6700, 0xff6700, 0x4d332f, "TIMER" },
    { 0xe00000, 0xe00000, 0x4d2632, "BREAKPOINT" },
    { 0xe5ff00, 0xe5ff00, 0x474d2f, "RANDOM" },
    { 0xff00bf, 0xff00bf, 0x4b214f, "WIRELESS_0" },
    { 0xff00af, 0xff00af, 0x4b214e, "WIRELESS_1" },
    { 0xff009f, 0xff009f, 0x4c214c, "WIRELESS_2" },
    { 0xff008f, 0xff008f, 0x4d2249, "WIRELESS_3" },
    { 0x66788e, 0x66788e, 0x66788e, "CROSS" },
    { 0x535572, 0x535572, 0x535572, "TUNNEL" },
    { 0x646a57, 0x646a57, 0x646a57, "MESH" },
    { 0x3a4551, 0x3a4551, 0x3a4551, "DECORATION" },
    { 0x8caba1, 0x8caba1, 0x8caba1, "FILLER" },
    { 0x7a2f24, 0xff2700, 0x542e35, "BUS_0" },
    { 0x3e7a24, 0x54ff00, 0x334d33, "BUS_1" },
    { 0x24417a, 0x005bff, 0x24315b, "BUS_2" },
    { 0x25627a, 0x00bfff, 0x1e3d5c, "BUS_3" },
    { 0x7a2d66, 0xff00c2, 0x522556, "BUS_4" },
    { 0x7a7024, 0xffe500, 0x4f4932, "BUS_5" },
    { 0x2a3541, 0x333e49, 0x2a3541, "TRACE_GRAY" },
    { 0x9fa8ae, 0xefefef, 0x3c4249, "TRACE_WHITE" },
    { 0xa1555e, 0xff384f, 0x5a444b, "TRACE_RED" },
    { 0xa16c56, 0xff753e, 0x5a4b45, "TRACE_ORANGE" },
    { 0xa18556, 0xffb83e, 0x5a5245, "TRACE_YELLOW_WARM" },
    { 0xa19856, 0xffe93e, 0x5a5845, "TRACE_YELLOW_COLD" },
    { 0x99a156, 0xebff3e, 0x585a45, "TRACE_LEMON" },
    { 0x88a156, 0xbfff3e, 0x535a45, "TRACE_GREEN_WARM" },
    { 0x6ca156, 0x78ff3e, 0x4b5a45, "TRACE_GREEN_COLD" },
    { 0x56a18d, 0x3effcc, 0x455a54, "TRACE_TURQUOISE" },
    { 0x5693a1, 0x3edbff, 0x45565a, "TRACE_BLUE_LIGHT" },
    { 0x567ba1, 0x3e9eff, 0x454f5a, "TRACE_BLUE" },
    { 0x5662a1, 0x3e7eff, 0x45485a, "TRACE_BLUE_DARK" },
    { 0x6656a1, 0x9b53ff, 0x49455a, "TRACE_PURPLE" },
    { 0x8756a1, 0xcc3eff, 0x53455a, "TRACE_VIOLET" },
    { 0xa15597, 0xff40e5, 0x5a4457, "TRACE_PINK" },
    { 0x2e475d, 0x63b1ff, 0x2e475d, "READ" },
    { 0x4d383e, 0xff5e5e, 0x4d383e, "WRITE" },
};

const size_t TC_COLOR_TABLE_LEN = sizeof(TC_COLOR_TABLE) / sizeof(TC_COLOR_TABLE[0]);

int TC_resolve_color(uint32_t editor, uint32_t* on, uint32_t* off) {
    for (size_t i = 0; i < TC_COLOR_TABLE_LEN; i++) {
        if (TC_COLOR_TABLE[i].editor == editor) {
            if (on)  *on  = TC_COLOR_TABLE[i].on;
            if (off) *off = TC_COLOR_TABLE[i].off;
            return 1;
        }
    }
    if (on)  *on  = 0;
    if (off) *off = 0;
    return 0;
}
